In [1]:
import pandas as pd
import numpy as np
import random
from statsmodels.stats.weightstats import ztest

In [2]:
data = pd.read_csv("train_data.csv")
data

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,0,1,0,1,0.2750,0.014151,0,0,1,0.1,1,0,0,0,0,0,1
1,1,2,1,0,0.4750,0.139136,1,0,0,0.1,1,0,0,0,1,0,0
2,2,3,1,0,0.3250,0.015469,0,0,1,0.0,0,0,0,1,0,0,1
3,3,4,1,0,0.4375,0.103644,1,0,0,0.1,1,0,0,0,0,0,1
4,4,5,0,1,0.4375,0.015713,0,0,1,0.0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,787,788,0,1,0.1000,0.056848,0,0,1,0.5,0,0,1,0,0,1,0
788,788,789,1,1,0.0125,0.040160,0,0,1,0.3,0,0,1,0,0,0,1
789,789,790,0,1,0.5750,0.154588,1,0,0,0.0,1,0,0,0,1,0,0
790,790,791,0,1,0.3500,0.015127,0,0,1,0.0,1,0,0,0,0,1,0
791,791,792,0,1,0.2000,0.050749,0,1,0,0.0,1,0,0,0,0,0,1

In [3]:
data_p1 = data[data['Pclass_1'] == 1]
data_p23 = data[(data['Pclass_2'] == 1) | (data['Pclass_3'] == 1)]
data_p1

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
1,1,2,1,0,0.4750,0.139136,1,0,0,0.1,1,0,0,0,1,0,0
3,3,4,1,0,0.4375,0.103644,1,0,0,0.1,1,0,0,0,0,0,1
6,6,7,0,1,0.6750,0.101229,1,0,0,0.0,1,0,0,0,0,0,1
11,11,12,1,0,0.7250,0.051822,1,0,0,0.0,0,0,0,1,0,0,1
23,23,24,1,1,0.3500,0.069291,1,0,0,0.0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,766,767,0,1,0.3500,0.077294,1,0,0,0.0,1,0,0,0,1,0,0
779,779,780,1,0,0.5375,0.412503,1,0,0,0.1,1,0,0,0,0,0,1
781,781,782,1,0,0.2125,0.111257,1,0,0,0.1,1,0,0,0,0,0,1
782,782,783,0,1,0.3625,0.058556,1,0,0,0.0,1,0,0,0,0,0,1
789,789,790,0,1,0.5750,0.154588,1,0,0,0.0,1,0,0,0,1,0,0

In [4]:
data_p1['Survived'].mean(), data_p23['Survived'].mean()

(np.float64(0.616580310880829), np.float64(0.3121869782971619))

In [5]:
ships = []

for _ in range(10000):
    p1 = pd.Series(random.choices(data_p1['Survived'].values, k=data_p1.shape[0])).mean()
    p23 = pd.Series(random.choices(data_p23['Survived'].values, k=data_p23.shape[0])).mean()
    ships.append(p1 - p23)

In [6]:
np.quantile(ships, q=[0.025, 0.975])

array([0.22673216, 0.38228935])

In [7]:
(data_p1['Survived'].mean() - data_p23['Survived'].mean()) / ((data["Survived"].mean() * (1 - data["Survived"].mean())) / (len(data['Survived']))) ** 0.5

np.float64(17.59316840863016)

In [8]:
ztest(data_p1.Survived, data_p23.Survived)

(np.float64(7.830586337563221), np.float64(4.855999313122105e-15))